#Informacion de la conecciona la base de datos

#Nombre de Base de datos
db.name=animecandles_db

#Informacion de usuario por defecto - Debe cambiarse por las que utilizamos en workbench
db.user=root
db.password=root

# Localhost y puertos 3306 utilizados por defecto pero puden cambiarse por los utilizados
db.host=localhost
db.port=3306